# Generated by Django 3.2.2 on 2021-05-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextHist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_text', models.CharField(max_length=100, null=True)),
                ('current_text', models.CharField(max_length=100)),
            ],
        ),
    ]
